### ISSUE TITLE
"Failed to check device" Error in web-ui

### ISSUE THREAD

**Issue by dreeco** [marian-m12l/studio#9]
After following the readme step by step, I have an issue while trying to read my Lunii's* library (I'm using version 0.0.2).

Error "Failed to check device" appears. 

When I look at Chrome's output console It seems that there is 2 issues : 
### 403 using websockets 
![image](https://user-images.githubusercontent.com/7996945/66890696-3bb96380-efe7-11e9-8c89-8d022b705e71.png)

### Error while parsing a JSON Object
It happens on /api/device/infos and here is the error output : 
```
Matron!
500 Illegal type in JsonObject: class com.lunii.device.wrapper.model.StoryTeller$FirmwareVersion
io.vertx.core.json.Json.checkAndCopy(Json.java:265)
io.vertx.core.json.JsonObject.put(JsonObject.java:684)
studio.webui.service.StoryTellerService.deviceInfos(StoryTellerService.java:98)
studio.webui.api.DeviceController.lambda$apiRouter$2(DeviceController.java:35)
io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:227)
io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:121)
io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:154)
io.vertx.ext.web.impl.RouterImpl.handleContext(RouterImpl.java:256)
io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:227)
io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:121)
io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:154)
io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.doEnd(BodyHandlerImpl.java:296)
io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.end(BodyHandlerImpl.java:276)
io.vertx.ext.web.handler.impl.BodyHandlerImpl.lambda$handle$0(BodyHandlerImpl.java:87)
io.vertx.core.http.impl.HttpServerRequestImpl.doEnd(HttpServerRequestImpl.java:537)
io.vertx.core.http.impl.HttpServerRequestImpl.handleEnd(HttpServerRequestImpl.java:526)
io.vertx.core.http.impl.Http1xServerConnection.handleEnd(Http1xServerConnection.java:167)
io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:136)
io.vertx.core.net.impl.ConnectionBase.handleRead(ConnectionBase.java:390)
io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:188)
io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:174)
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:102)
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
java.base/java.lang.Thread.run(Thread.java:830)
```

Official Luniistore* is working properly and Ihave "Succeeded in deploying verticle" success message : 
![image](https://user-images.githubusercontent.com/7996945/66890844-bda98c80-efe7-11e9-9421-5f143f9bb135.png)

I'm using windows, have jdk 13.0.1 installed and have just refreshed an token.
I've tried with both Luniistore* program running / not running (it seems that it's best when Luniistore* is not running).

Am I missing something ?

**Comment by dreeco** [comment]
![image](https://user-images.githubusercontent.com/7996945/66906063-43890000-f007-11e9-9547-73e0ab4d50c3.png)
Maybe the firmware has changed its implementation of "getFirmwareVersion" and the type cannot be converted into json by vertex library ? Maybe a ToString() could fix it ?

**Comment by dreeco** [comment]
.toString() fix the issue but its not some displayable value (it displays the name of the class) . The path to build url images, description, etc. is also broken because official.json format has changed. I Haven't tried to upload a story on my Lunii's yet but will sure do soon :)

**Comment by marian-m12l** [comment]
Hi,

Sorry for the delay, I just noticed your issue... Need to fix my github notifications !!

Thanks for your feedback. It certainly looks like `getFirmwareVersion()` has changed. I'll have a look when I can plug the Lunii again. Although IIRC my own device returned a null or empty value for firmware version. Would you mind adding some logging to see what your version looks like? Anyway, I can also just remove that bit of data as it's just there to display some info about the plugged Lunii.

I'll need to have a look at the metadata file format too...

Please let me know if you've tried to build and upload a story. Or if you need assistance... I know the tool is still pretty rough to install and use... :-)

**Comment by marian-m12l** [comment]
@dreeco I published a new version which should fix your issues (firmware version and metadata from official.json). Although as I said in my previous message, with my own device I get a `null` version, so I cannot verify that the major and minor versions appear correctly with other devices.

Please let me know if it fixes your issues.

**Comment by dreeco** [comment]
Hello, I also need to fix my notifications :)

Your documentation is very clear ! I could build and pass through those error (without actually fixing the code) very easily.

I haven't tried your updated version but hopefully will around lunchtime.

This morning I tried to package a story then reload it in the webview and it did not work (it was a zip and the error said that only zip were accepted). I had trouble with MP3 but could finally load audio files in ogg.

I have trouble exactly understanding the node view but your sample is great and I just need some time. I was amazed by the preview functionality.

It's a great tool. Thank you very much for it. 

I will try and debug the firmware object. If you need any help please don't hesitate. I have very little experience with Java but I'm a programmer, I sure can help you in some way !

Cheers

**Comment by marian-m12l** [comment]
Thanks for your feedback, glad you appreciate it. I definitely had some fun making the pack viewer :-)

For the zip file, my guess would be that your combination of OS/browser uses a different mime type than the app checks (`application/zip`). You could add some logs before the check around here : https://github.com/marian-m12l/studio/blob/50ce71560da550bf99e7b8f43a756c843d0674b9/web-ui/javascript/src/components/diagram/PackEditor.js#L148
Also, you might want to check that the zip file is not corrupt or something.
In the new version, you'll see that the workflow is now to open and save packs from the "local library" instead of having to download and upload the zip files.

Did you get errors with MP3 files ? Should be supported. BTW I added a few infos about the asset format in the readme (those supported by my own "archive"/zip format and the editor, and those supported by the Lunii itself -- conversion is done if needed before uploading a pack to the device). I should also add a few "tips" about the audio assets to get the right volume and delay.

The diagram view is...well... not particularly user-friendly, to put it mildly. The graph itself is really close to the actual file format of the story packs, and I had to come up with those not-so-intuitive stage and action concepts. In the future, I think a good part of all this could be hidden behind higher-level nodes (hiding uninteresting action nodes and links to go back, setting the flags correctly depending on the expected behaviour, etc.), and make it more foolproof. That's basically why I load an example by default, so that one can try to understand by himself, and maybe just duplicate some nodes, until I take the time to write some usage doc.

Thanks for offering your help. Right now, I'll take any feedback, be it bug reports or enhancement requests or whatever. Feel free to create new issues (or even PRs). The existing issues are pretty much long-term features that require significant work, so not ideal to get onboard... When you're done "grasping" the diagram / node view, I'd love to hear your opinion and talk about improvements.

**Comment by marian-m12l** [comment]
@dreeco btw, I commented on the tsukuyomi chatroom ;-)

**Comment by dreeco** [comment]
Thank you for your answer.

- I think MP3 problem is an encoding issue (192kbit/s) can it be ? Still OGG is okay so I'm not stuck on that
- I think I am grasping the concept of nodes. Good for me.
![image](https://user-images.githubusercontent.com/7996945/68687415-6efefc00-056d-11ea-900c-32ba9aeca9b1.png)
- Images are OK. Thank you for the 24bits precision
- Zip still does not work but I haven't checked the mime type
- I can't save to library (it says ok but there is nothing in my local folder). I'm on windows if it helps.
- I copied pasted the zip to the library and tried to update it but is does not work.
![image](https://user-images.githubusercontent.com/7996945/68687356-57c00e80-056d-11ea-924a-885cdde928d9.png)
It seems a CORS issue. I don't know how to fix it

**Comment by dreeco** [comment]
I've tried to run it in chrome without CORS enabled and still have the issue. Here is the console logs when I open http://localhot:8080 :
![image](https://user-images.githubusercontent.com/7996945/68687855-1da33c80-056e-11ea-9f86-262c4e434f05.png)

**Comment by marian-m12l** [comment]
@dreeco I just released version 0.0.4, which should fix:
- The CORS issue, which may be the cause of other issues (like saving to library, maybe)
- The zip mimetype when importing a pack in the editor
- The mimetypes for wave and mp3 files

I tested on Windows 10 / Chrome 78 and it seems OK now.

Looks like you're doing well with the node graph! Great! You'll see that the devil is in the details, such as the "flags" to enable or disable the controls, and the OK/Home transitions. Which is why I want to simplify all this. I'll try and update the related issue with some more details of what I'm envisioning.

About the MP3, I didn't perform extensive tests, so I guess some encoding or particular formats may cause issues. However, that does not happen until you try to transfer the pack to the device. That's when the conversion happens. In the editor, that's just the browser playing the audio file. Maybe try again now that I fixed some mimetype checks? Otherwise, if it's a file that you created, maybe you could supply me with a bit of file to reproduce the bug?

Thanks again for the feedback! Greatly appreciated!

**Comment by marian-m12l** [comment]
Forgot to commit another change so that the pack is saved correctly with the new mimetypes. Use the latest release : https://github.com/marian-m12l/studio/releases/tag/0.0.5

**Comment by dreeco** [comment]
Thanks a lot for that update !! Its working pretty well : 
- I can copy both MP3 and OGG
- loading zip is working as well, saving to library as well
- I can load the pack into my daughter's Lunii.
But there is still an issue. All my nodes are working but not the final ones (the story). I've tried both OGG and MP3 and its the same. The lunii seems to be playing something (or is waiting for something) but no sound come out of the Lunii. 
In the emulator that you've made, everything is perfect !
The weird thing is that all my audio files has been processed exactly the same (recorded on my phone, then converted to OGG by an online tool). The menu plays well but not the stories :(

**Comment by dreeco** [comment]
You'e been a great help ! I'm gonna try to encode it differently for now. Thanks

**Comment by marian-m12l** [comment]
Great!

That's a bit strange, the stories not playing... Here are a few stuff you may look at :
- How long are the audio files ? I tried it with stories of a minute or two. I add about 2 seconds of delay at the beginning.
- What is the sample rate, bitsize, number of channels ?
- Probably with no effect, but you may try playing with the control flags on the story nodes. I use Home/Pause/Autoplay enabled on a story node.  The OK button is generally linked to the main question at the beginning of the pack, so that when the story ends, the Lunii does goes on for to make another story. The HOME button is not linked to anything, which means "go back to the first node" (pack selection).

**Comment by dreeco** [comment]
- My stories are about 5 minutes. Is it too long ? I'll try with shorter ones
- Sample rate is 44100khz, 32 bits per sample, channels stereo (2 ?)
![image](https://user-images.githubusercontent.com/7996945/68710240-763aff80-0597-11ea-9a48-09f452e20528.png)
- I've tried what you said about control flags, with no effect.

**Comment by dreeco** [comment]
I've tried with bitrate 32kb/s and less than 2 minutes and I have the same issue. I think I'm missing something with the nodes

**Comment by marian-m12l** [comment]
This shouldn't cause problems as it's supposed to be converted, but you can try in mono and/or 32000Hz.
To see if this is a node graph problem, maybe use an audio file that you know for sure works in the previous nodes?

**Comment by dreeco** [comment]
Ok, the sound is OK, definitely a problem with my nodes :) 
I now have an "/!\ ERROR" displayed with a weird sound when I do a selection.
I'm gonna fix this tomorrow. Thank you a lot for your help !

I've had some ideas / bug fixing that are not related to this one. Maybe we can close the issue ?

**Comment by marian-m12l** [comment]
OK. You're right, I'm closing this issue. Lmk if I can help.
The error image means the generated pack (in lunii format) must be corrupt. Probably something that could be catched by checking the pack graph more thoroughly before converting to lunii format. In this case I think it would be more efficient to have the particular pack file. Or a minimal pack that reproduces the error.

**Comment by dreeco** [comment]
Hi, I'm still having issues about having a pack fully working on the device. I'm not sure where to continue the conversation...

I could give you the pack I'm having trouble with if you still want to help me debug it

**Comment by marian-m12l** [comment]
Hi,

Sure, I'd like to find out what's not working. I guess we can continue using this issue. Can you attach the pack file? Otherwise you can email me at muller.marian at gmail dot com
